//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace news365.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageTable
    {
        public int Img_id { get; set; }
        public string Image { get; set; }
        public string Text { get; set; }
    }
}
